
package com.exxeta.ejb.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TeilnehmerSoapService", targetNamespace = "http://ejb.exxeta.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TeilnehmerSoapService {


    /**
     * 
     * @return
     *     returns java.util.List<com.exxeta.ejb.client.Teilnehmer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllTeilnehmer", targetNamespace = "http://ejb.exxeta.com/", className = "com.exxeta.ejb.client.FindAllTeilnehmer")
    @ResponseWrapper(localName = "findAllTeilnehmerResponse", targetNamespace = "http://ejb.exxeta.com/", className = "com.exxeta.ejb.client.FindAllTeilnehmerResponse")
    public List<Teilnehmer> findAllTeilnehmer();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.exxeta.ejb.client.Teilnehmer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findTeilnehmerById", targetNamespace = "http://ejb.exxeta.com/", className = "com.exxeta.ejb.client.FindTeilnehmerById")
    @ResponseWrapper(localName = "findTeilnehmerByIdResponse", targetNamespace = "http://ejb.exxeta.com/", className = "com.exxeta.ejb.client.FindTeilnehmerByIdResponse")
    public Teilnehmer findTeilnehmerById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
